#!/usr/bin/env bash

NPROC=$(awk '/cpu cores/ {print $4; exit}' /proc/cpuinfo 2>/dev/null || sysctl -n hw.ncpu)

function process_template() {
  test -d $(dirname "build/$1") || install -d -D $(dirname "build/$1")
  echo "Processing: ${1}"
  m4 $1 > build/$1
}
export -f process_template

find . -name '*.html' -type f -not -path './build/*' \
  | xargs -n1 -P ${NPROC} -I {} bash -c 'process_template "$@"' _ {}
